<?php
// modules/backup/proses.php - Generate SQL backup
check_user_level(['admin']);

header('Content-Type: text/plain; charset=utf-8');
header('Content-Disposition: attachment; filename="backup_banksampah_' . date('Y-m-d_H-i-s') . '.sql"');

echo "-- Backup Bank Sampah Digital\n";
echo "-- Tanggal: " . date('Y-m-d H:i:s') . "\n";
echo "-- Generated by: " . htmlspecialchars($_SESSION['user_nama']) . "\n\n";

echo "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
echo "START TRANSACTION;\n";
echo "SET time_zone = \"+07:00\";\n\n";

$tables = ['pengguna', 'jenis_sampah', 'transaksi', 'detail_setoran', 'log_aktivitas', 'harga_history'];
foreach ($tables as $table) {
    $result = mysqli_query($koneksi, "SHOW CREATE TABLE `$table`");
    if (!$result) continue;
    $row = mysqli_fetch_assoc($result);
    echo "\nDROP TABLE IF EXISTS `$table`;\n";
    echo $row['Create Table'] . ";\n\n";

    $data = mysqli_query($koneksi, "SELECT * FROM `$table`");
    while ($row = mysqli_fetch_assoc($data)) {
        $cols = array_keys($row);
        $vals = array_values($row);
        $escaped = array_map(function($v) use ($koneksi) {
            return $v === null ? 'NULL' : "'" . mysqli_real_escape_string($koneksi, $v) . "'";
        }, $vals);
        echo "INSERT INTO `$table` (`" . implode("`, `", $cols) . "`) VALUES (" . implode(", ", $escaped) . ");\n";
    }
}

echo "\nCOMMIT;\n";
log_aktivitas('backup_database', null, null, "Backup database diunduh");
exit;
